account/urls.py
from django.urls import path

from .views import register_user, login_user, logout_user

app_name = 'account'

urlpatterns = [
    path('', register_user, name='register_user'),
    path('login_user/', login_user, name='login_user'),
    path('logout_user/', logout_user, name='logout_user'),

]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('main.urls')),

]

main/urls.py
from django.urls import path

from .views import index, create_student, student_update, student_delete

app_name = 'main'

urlpatterns = [
    path('index/', index, name='index'),
    path('create_student/', create_student, name='create_student'),
    path('update_student/<int:pk>/', student_update, name='update_student'),
    path('delete_student/<int:pk>/', student_delete, name='delete_student'),
]

account/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models


class Student(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=70)
    age = models.PositiveIntegerField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Student'
        verbose_name_plural = 'Students'

account/forms.py
from django import forms
from django.contrib.auth.models import User


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'password2')

    def clean_password2(self):
        cleaned_data = self.cleaned_data
        if cleaned_data['password'] != cleaned_data['password2']:
            raise forms.ValidationError('Incorrect password!!!')
        return cleaned_data['password2']


class LoginForm(forms.Form):
    username = forms.CharField(label='username')
    password = forms.CharField(widget=forms.PasswordInput)

main/forms.py
from django.forms import ModelForm

from .models import Student


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

account/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import login, authenticate, logout

from .forms import RegisterForm, LoginForm


def register_user(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect('account:login_user')
        return HttpResponse('Invalid form!!!')
    form = RegisterForm()

    context = {
        'form': form
    }
    return render(request, 'account/register_user.html', context)


def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("main:index")
            return HttpResponse('User not found!!!')
        return HttpResponse('Invalid form!!!')
    form = LoginForm()
    context = {
        'form': form
    }
    return render(request, 'account/login.html', context)


def logout_user(request):
    logout(request)
    return redirect('account:login_user')

main/views.py
from django.shortcuts import render, redirect, HttpResponse

from .models import Student
from .forms import StudentForm


def index(request):
    student = Student.objects.all()
    return render(request, 'main/index.html', {'student': student})


def create_student(request):
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:index')
        else:
            return HttpResponse('Error')

    form = StudentForm()

    context = {
        'form': form,
    }
    return render(request, 'main/create_student.html', context)


def student_update(request, pk):
    student = Student.objects.get(id=pk)

    if request.method == 'POST':
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect('main:index')

        return HttpResponse('Error')

    form = StudentForm(instance=student)

    context = {
        'form': form
    }
    return render(request, 'main/create_student.html', context)


def student_delete(request, pk):
    student = Student.objects.get(id=pk)
    student.delete()
    return redirect('main:index')

templates/main/create_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="features">
    <h1>Add students</h1>
    <form method="post">
        {% csrf_token %}
        {{form.name}}<br>
        {{form.surname}}<br>
        {{form.age}}<br>
        <button class="btn btn-success" type="submit">Добавить</button>
    </form>
</div>
</body>
</html>

templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student</title>
</head>
<body>
<div class="features">
    <h1>Students</h1>
    {% for el in student %}
    <div class="alert alert-warning">
        <h3>{{el.name}}</h3>
        <p>{{el.surname}}</p>
        <p>{{el.age}}</p>
    </div>
    <a href="{% url 'main:update_student' el.id %}">
        <button class="btn btn-success" type="submit">Update</button>
    </a>
    <a href="{% url 'main:delete_student' el.id %}">
        <button class="btn btn-success" type="submit">Delete</button>
    </a>
    {% endfor %}
    <br>
    <br>
    <br>

    <a href="{% url 'main:create_student' %}">
        <button class="btn btn-success" type="submit">Add new Student</button>
    </a>

    <br>
    <br>
    <br>
    <br>
    <br>

    <a href="{% url 'account:logout_user' %}">
        <button>Logout</button>
    </a>
</div>
</body>
</html>